### ISSUE TITLE
Request Jt-Com & Goodtop Switch

### ISSUE THREAD

**Issue by Virtualchronos** [OtisPresley/snmp-switch-manager#56]
Hello !

I'm using your integration since a few months and first let me thank you for your hard and quick work !!!

I would like to help you to add jt-com switches and also goodtop wich are not recognized properly (goodtop switch is recognized when nothing is specified on card and all entities disapeared when the correct type is specified). I'm not over-skilled but I'm available to help you anytime and provide you feedback on use.

Switch L2 Goodtop GT-SWTG242M (24 2.5Gb ports and 2 10Gb SFP ports)
- System OID : 1.3.6.1.4.1.27282.1.3   (written on the switch web interface)

Switch L3 Jt-com JT-FG6700-8TFM  (JT-S508CL-8S   clone) (8 10Gb SFP ports)

I hope thoses infos would help you, let me know if i can help in any way and we could do a screen share and talk directly if needed

**Comment by OtisPresley** [comment]
Hi @Virtualchronos, and thank you for using the integration and the card!

If you can paste a screenshot of an interface for each switch from the integration with the Attrributes expanded, that would be great. If that is all there, then your issue is only in the card. I have been thinking about providing a way for users to specify in the card configuration which interfaces are physical or virtual, but I need to also make sure that you are getting all the proper information via the integration.

**Comment by Virtualchronos** [comment]
a photo for each would be really long (26 ports + 8 Link aggregation) here's the list of the informations:

LAG 1 to 8 :

Index 1 000
Name LAG1
Alias Proxmox
Admin Up 
Oper Up
Speed 2.5 Gbps

Index 1 001
Name LAG2
Alias Proxmox 2
Admin Up
Oper NotPresent
Speed 1 Gbps

Index 1 002
Name LAG3
Alias Proxmox 3
Admin Up
Oper Up
Speed 1 Gbps

... the other ports are the same with LAG8 is index 1007



LAN 2.5GB ports 1 to 24 :

Index 1
Name MultiGigabitEthernet1
Alias Mikrotik
Admin Up
Oper Up
Speed 2.5 Gbps
IP 127.0.0.1/8

(the mikrotik is the only one to show an ip and this is wrong since it's ip is 192.168.1.1)

Index 2
Name MultiGigabitEthernet2
Alias Bridge Zigbee
Admin Up
Oper Up
Speed 1 Gbps

Index 3
Name MultiGigabitEthernet3
Alias
Admin Up
Oper Up
Speed 100 Mbps

... (the index continue to index 24)

Index 24
Name MultiGigabitEthernet24
Alias Sonnette
Admin Up
Oper Up
Speed 100 Mbps




SFP 1 & 2 :

Index 25
Name TenGigabitEthernet1
Alias
Admin Up
Oper Down
Speed 10 Gbps


Index 26
Name TenGigabitEthernet2
Alias
Admin Up
Oper Up
Speed 10 Gbps



Btw, is there a way to auto rename all the ports with ETH or SFP for 10GB connection and ETH or ethernet for slower connections ? the original naming is awfully long and painful to rename one entity at a time

**Comment by OtisPresley** [comment]
Hi @Virtualchronos, I have released  v0.3.4 of the card that hopefully fixes this for you. It also provides 2 fields to specify which interfaces are physical. 1 field is simple comma-separate strings and the other is regex. When regex is used, the simple field is ignored. Please let me know how it goes.

**Comment by Virtualchronos** [comment]
Sorry, the update is still bugged. the speed mode still shows the same false infos (i cleared browser cache after updating card to be sure) 
i'm available on jitsi for a screen share if you want

**Comment by Virtualchronos** [comment]
Hello !

- Speed color problem seems only related to card. The most strange thing is that when you click on the card it displays the correct info. The problem is more likely related to bad code in card speed color area. 
- I think, chosing a color is good enough but maybe black for inactive/ unplugged port could be good and red for manualy deactivated port. anyway a way to chose colors would be great.
- I'm no expert but the menu is kinda confusing for persons who doesn't know how to deal with switches. maybe some documentation or simpler explanations would help
- i would like an option to toggle which diagnostic info is displayed or not. manufacturer, firmware and model are nearly static infos that never change nor realy need to be displayed so an option to only show uptime and/or custom infos would be good
- for the squares and json positionning, honnestly the system is not great. as said before, you must click multiple times on each port for it to be displayed on json area. you also need to place it manually perfectly at the good place so it doesn't look bad on frontend and adjust it by changing x and y on each port so they are aligned... This option allow you to do what you want but it need a lot of work that maybe can be simplified ? 
- maybe another option to hide specific ports ? for example if i want to add LAG and i only use 2 LAGS, i don't want to add eight of them

**Comment by Virtualchronos** [comment]
- hard to understand parts : not the card part but the plugin side... A lot of config include specific terms that i didn't understood first. maybe some kind of more automated choices would be easyer or maybe a little bit of explanations inside the differents menus would help
- for the card alignment maybe some tools to adjust space between boxes and specify the order of the boxes and wich you'd like to implement or not ?

ex :
number of lines : 3 (would create immediatly the number of config lines depending of the chosen number)
ports numbers in the desired order separate by comas on line ("x"):     eth1, eth3, eth5
centered ? : yes (centered or aligned to the left)
line 1 offset X/Y : 0;0 (to offset all ports of the line to a certain coordinates)
space between each ports : 13
space between each lines : 13
######
ports numbers in the desired order separate by comas on line ("x+1"):     eth2, eth4, eth6
centered ? : yes
line 2 offset X/Y : 0;0
space between each ports: 13
space between each lines : 13
######
ports numbers in the desired order separate by comas on line ("x+2"):     sfp1, sfp2
centered ? : no
line 1 offset X/Y : 150;0
space between each ports: 200
space between each lines : 13

this tool would allow to adjust automatically the space and chose ports shown or not and in the desired order without the need of snapping tool (even if it would also be great) but would need less code to do from your side. Of course the user could also use the json tool to specify custom coordinates wich would solve any case.

- for the sensor it was a guess from me i didn't tried first. the problem is that if you put speed datas in diag it create a lot of new sensors (+80 for my switch if i remember well) this makes the data read hard and should be kept inside ports attributes with the other datas to keep it simple and easy
- I've spot another bug from the card : I've changed ports names by the method you've told me and... The card doesn't recognized them anymore when i select my switch... This is the second time i've got this bug. when i dont select device in switch card it find entities but as soon as i select my switch it picks random entities like the heater or sound devices...

**Comment by OtisPresley** [comment]
Would you be available at 4 or 5PM your time tomorrow?

**Comment by Virtualchronos** [comment]
yes, i'll be available for sure. 
(the problems come from the card i'm sure of it since the integration give perfect infos, only the card is totaly messed up). i'll show you tomorow, htere's plenty of things that makes it very hard to use, i'm still on it i couldn't quit finally but the more i dig and the more i find problems T.T

**Comment by Virtualchronos** [comment]
Hello ! 
I'm available for jitsy

**Comment by OtisPresley** [comment]
https://us05web.zoom.us/j/85374383811?pwd=oYtZ9ufavBpIn9i49BYpC3SUGUZRmt.1

**Comment by Virtualchronos** [comment]
Hello !
Very good release !

Outline is PERFECT ! Maybe just an option to increase outline size if i want to be picky (or chose between thin medium and large outline). But it gives instant readability on every color wich is wonderful
pixel snap seems to work so far
port gap doesn't seems to have changed anything since it only change card height
card still not scale and stack on top of each other
numbers only and no label work perfectly and make everything readable on 4k and on phone
label positionning inside the squares isn't perfectly centered but that's not a big deal
labels are now moving in sync with ports ! 
there's still a bug with odd-even and numeric (the option sometimes makes no change at all and it stays in odd-even position) when it accepted to redo in numeric order, the squares disposition seems to glue every square by line like before...

for the unknown switch bug, i must mess-up my switch again before telling you if it is still present

**Comment by OtisPresley** [comment]
Thanks! What I discovered with port gap is that it works until it runs out of width, and then it goes vertical only. I made the card height scale with the content, so if you move something beyond the edge and save, it will increase the height of the card, so I am surprised they still overlap for you.

For the numbers, I switched to just using the numbers at the end of the string. The reason I don't use ifIndex is because not every vendor keeps them aligned with the port numbers, so allowing a choice here would be best.

I will look into the alignment of the labels inside the ports.

Odd/Even and Numberic still require you to move the ports a little before it re-orders them. I am still looking into that one, and I will look into undo redo logic more.

I will change it so that Disconnected is always an option.

I am glad this corrected most things for you.

**Comment by Virtualchronos** [comment]
hello !
i've not much time tonight , i'll make you a deeper review tomorow. 
Some new features are not working at all or not as intended. for the colors, don't forget to also add admin deactivated port color wich is very important (all the function from the other mode in summary). 
See you tomorow ^.^

**Comment by Virtualchronos** [comment]
- environmental sensor : showing "0 W" for me... either it's not working or both of my switchs doesn't use it
- Unfortunately i do not own POE switchs so i can't help you on this side
- Bandwidth sensors : each mode seems to work as intended ! (a graph for the card would be great when you click on a port but i don't know if it's possible
- speed color are good and also change when ethernet is unplugged but if you admin disable the port it switch to the max port speed color for L2 switch and stays on disconnected color on L3 switch (if admin disabled port, then color = admin disabled port color regardless of the speed anounced)
- missing colors setup for the not used speed (unplugged is presentand admin mode. All the options should be available instead of just the one displayed on the card
- horizontal port gap doesn't seems to do anything... and vertical is still doing the same thing (redimmentionning the height without spacing the ports). EDIT : working after the renaming entities bug (read below) ?!? (Gap bug related to ports names ?)
- label font & bacgroung color work
- add sensor to diagnostic : WORKING
- Show uplinks separately in layout : I'm too dumb tu understand exactly what it does XD
- hide port : working
- Vlan : still only one Vlan showing
- updating integration removed the custom renaming rules (still present in settings but not applied, every named returned to it's original value)
- Auto integration icons from entities name renamed all entities back to their original name : NOT WORKING
- big mess in naming ports system after integration icon : only one rule of naming is applied, others are ignored...
- restore built-in name option : Not working
- MultiGigabitEthernet named ports doesn't show anymore on card (must rename them to 2.5G before they are shown)
- when you name a port 2.5G or 10G , the space after the 'G' ( '10G ' to have a port named "2.5G 12" instead of "2.5G12") is applied which is great but the space is ignored when renaming a port

A lot of the card bugs seems related to old datas stored in card or integration... As soon as the entities names change or recreation of the layout is activated, the behaviour of the card can change drastically... Icon size change, ports disappearance and other odd things happenning randomly. 
I don't know if it's pertinent to continue the tests further (at least for today) untill the card datas handling isn't more stable (standardized datas between revisions ?). I'm pretty sure some old settings are stored in card and since i'm an old user, the old settings are saved and messing with the new config options.

**Comment by OtisPresley** [comment]
I did some preliminary responses on your list:

- environmental sensor : only added one entity showing "0 W" for me... either it's not working or both of my switchs doesn't use it. Strange thing, the l2 switch displays on it's frontend the ram and CPU usage... either the integration isn't able to find it or it ins't sent by snmp)
  - This is an SNMP issue. You would have to find the correct MIB/OID if it is exposed by your switch. I had to do a lot of research to nail down mine.
- Unfortunately i do not own POE switchs so i can't help you on this side
  - No problem, but the same thing with SNMP as above
- Bandwidth sensors : each mode seems to work as intended ! (a graph for the card would be great when you click on a port but i don't know if it's possible
  - When your Port color is set to Speed, there is an "option for Open traffic graph on port click" That bypasses the port information box and opens the traffic graph. This only works when Bandwidth Sensors are set to Sensors. Attributes do not have a history in HA.
- speed color are good and also change when ethernet is unplugged but if you admin disable the port, it switch to the max port speed color for L2 switch and stays on disconnected color on L3 switch (if admin disabled port, then color = admin disabled port color regardless of the speed anounced)
  - If I am understanding correctly, you want Speed mode to only change the color for ports that are not admin disabled. If they are admin disabled, then change the color to the Admin Down color, which should also be shown in Speed mode in the configuration?
- missing colors setup for the not used speed (unplugged is present) and admin mode. All the options should be available instead of just the one displayed on the card
  - I can add a button that will show all supported speeds instead of just detected ones. Would that work?
- horizontal port gap doesn't seems to do anything... and vertical is still doing the same thing (redimmentionning the height without spacing the ports). EDIT : working after the renaming entities bug (read below) ?!? (Gap bug related to ports names ?)
  - This is expected behavior when it runs out of horizontal space in the panel. I will see what I can do about your allow panel width to scale idea.
- Show uplinks separately in layout : I'm too dumb tu understand exactly what it does XD
  - On switches, sometimes there are special ports for connecting to routers or other switches that are called Uplinks. In the card, this just means that the ports specified will not be included in the box when Ports is turned on or with the other ports when the layout is reset.
- Vlan : still only one Vlan showing
  - I think we are going to need some SNMP information from your switch to fix this.
- updating integration removed the custom renaming rules (still present in settings but not applied, every named returned to it's original value)
  - That is not good. Thanks for letting me know.
- Auto integration icons from entities name renamed all entities back to their original name : NOT WORKING
  - That's not ideal either. It is not supposed to be tied together.
- big mess in naming ports system after integration icon : only one rule of naming is applied, others are ignored... edit : in fact the second rule had been replaced with the content of the first one ?!?
  - I will investigate
- restore built-in name option : Not working
  - How so? What is happening?
- MultiGigabitEthernet named ports doesn't show anymore on card (must rename them to 2.5G before they are shown)
  - Do you have Virtual interfaces added in the card config?
- when you name a port 2.5G or 10G , the space after the 'G' ( '10G ' to have a port named "2.5G 12" instead of "2.5G12") is applied which is great but the space is ignored when renaming a port
  - Oh, thanks for letting me know. This update was a lot of late nights.
- in card settinge, arrows up/down to augment or reduce a number are uselessly tiny in 4k web view
  - I will see about scaling them
- outline is only available for numbers only and not for labels (grayed switch in label mode)
  - Ahhh, I had thought you only wanted it for numbers. I will expand it.
- number from port name doesn't work or at least doesn't switch
  - Are the numbers in your port names different than the Index numbers? How do you know?
  
**Ameliorations ideas :**

- Auto change pannel Width based on layout
  - I will look into it to see if it has any undesired side effects.
- Auto center layout (first port is often at "horizontal spacing" pixels from the left, it leads to a fixed distance from the left but very close or far from the right depending on pannel widht)
  - I would think that is expected behavior?
- I don't know for others but when you use a switch, you don't plug and unplug ports twice a day... The config stays the same for weeks or even months which lead me to this idea :
  - Auto "add ONLY USED ports bandwidth sensors" (if port is unplugged/admin disabled, the sensors related aren't added which would lower H-A charge
   and also limit a ton of useless sensors added)
    - Do you mean initially or dynamically as ports transistion from down to up?
  - Auto "remove Unused ports bandwith sensors if port unused since X-days" (number of days chosen by user)
    - I will look into that
- Ip of the device connected to each port
  - I have thought about this and it depends on if this is exposed in SNMP. I was considering doing this in another automation that creates a map of your network based on this and detect if these devices already exist in HA, like by MAC and/or IP
- mac address of the device connected to each port inside port data or sensor(would allow automations such "if mac addres of port 12 isn't 00:3f:4d:A7, then deactivate port and ring alarm)
  - Same as above
- i checked the speed bug of the switch L2 and sent speed seems good, on the snmp side, the ifspeed of disconnected ports is 0 which is totally normal, so maybe there's a thing that isn't working on integration side ? if needed, i created an 3.2mb xml file of snmp protocol that i can send to you via virola
  - This should be based on Operational state. If the port is Up/Down, Down/Down, or Admin Down, then speed should be set to Disconnected.
- A lot of the card bugs seems related to old datas stored in card or integration... As soon as the entities names change or recreation of the layout is activated, the behaviour of the card can change drastically... Icon size change, ports disappearance and other odd things happenning randomly.
  - We will need to do more discovery on this.

**Comment by OtisPresley** [comment]
Thanks for this! I have tried to address the integration bugs first in **v0.4.1-beta.1**. Please let me know if this fixes your issues or if I have missed any bugs. Once we get bugs squashed, I will work on feature enhancements.

**Comment by Virtualchronos** [comment]
can you list me the fixes you've done ? i don't find any change and i réupdated card and integration

**Comment by OtisPresley** [comment]
I have released v0.4.1-beta.1 of the card that fixes Save and Autoscaling (Panel width set to 0). There is some extra vertical margin that is unavoidable when autoscaling. I will try and find some time tomorrow to ping you on Virola to work through the issues you are having.

**Comment by OtisPresley** [comment]
Hello @Virtualchronos, I have released card **v0.4.1-beta.2** for you to try. I had to abandon trying to make the reset layout behavior work without having to hit reset layout each time to see the changes. This has to do with the way it has to deal with custom port positions.

I also was unable to make Port scale work correctly with autoscaling. It just always goes to 1, which is not useful. I have not cracked that one yet. Autoscaling should work for Panel width, Horizontal gap, and Vertical gap though by setting the value to 0.

**Comment by Virtualchronos** [comment]
Hey 👋 
I hope you have took a little rest because you've been very active lately! I'm gonna try the latest version and give you feedback as soon as I can 👍

**Comment by Virtualchronos** [comment]
new integration or still the same ?

**Comment by OtisPresley** [comment]
Oh, not an integration at all. I am just working to make my HA automation smarter by centralizing a lot of its decision making. I am planning to make it portable eventually, but some of it is still pretty specific to the way I use HA.

**Comment by Virtualchronos** [comment]
Hello !

Bad news, your latest update broke some sensors and this time it doesn't seems to be related to the cards... speed is not correct on all ports and it created a void duplicata of each of my switchs with no entities...?
furthermore, view speed of each port is not available anymore in the plugin webpage... 

i'm available if you want to check it ^^

**Comment by OtisPresley** [comment]
Thanks @Virtualchronos! I am looking into it

**Comment by Virtualchronos** [comment]
We should plan a meet so I can show you the strange behavior

**Comment by OtisPresley** [comment]
Hi @Virtualchronos, there has been a lot going on. I hopefully have a fix for you. I just need to incorporate a couple more fixes before generating a beta release for you to test. Thank you for your patience.

**Comment by Virtualchronos** [comment]
No problem, I'm not in a hurry. The only problem with the new release is that it doubled my switch entities and now I Don't know what to do

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by OtisPresley** [comment]
Hi @Virtualchronos, I have released v0.5.2-beta.1. Please delete the duplicated devices and reboot to see if it is back to normal for you.

**Comment by Virtualchronos** [comment]
can't delete the entites T.T, only deactivate them

<img width="2575" height="1800" alt="Image" src="https://github.com/user-attachments/assets/e1a5860c-14ca-4bac-aac1-593fa4559cbd" />

**Comment by OtisPresley** [comment]
OK, I will see if I can implement a cleanup routine that gets rid of them if they are present.

**Comment by OtisPresley** [comment]
Hi @Virtualchronos, I have released a new beta, [v0.6.0-beta.1](https://github.com/OtisPresley/snmp-switch-manager/releases/tag/v0.6.0-beta.1),  on a different branch where I have overhauled the integration if you would like to test it. It should have a cleanup routine in it that will safely remove your duplicate devices. There are a couple bugs I am still working out with submitting certain things to the database for community use, but I hope all else works for you.

**Comment by OtisPresley** [comment]
Hey @Virtualchronos, I will go ahead and close this. Please open a new issue or re-open this one if you have any problems.
